### ISSUE TITLE
how to read  request header map ?

### ISSUE THREAD

**Issue by jilieryuyi** [keyval-dev/opentelemetry-go-instrumentation#13]

**Comment by edeNFed** [comment]
Hi @jilieryuyi,
I am not sure I fully understand your question.
Are you asking how to add the headers of the HTTP request to the produced span? 
This can be achieved by modifying the HTTP instrumentor for example:
https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/master/pkg/instrumentors/bpf/net/http/server/probe.go

to read the `Header` field of the `http.Request` struct and to add the map contents into the produced span.

Notice that because this is a new field that none of the other instrumentors use, it needs to be tracked by offsets-tracker:
https://github.com/keyval-dev/offsets-tracker/blob/19f19f58020255b5f12585055076cefbc637c0c1/main.go#L18
